### ISSUE TITLE
2nd round of scaffolding error

### ISSUE THREAD

**Issue by PedroBarbosa** [ksahlin/BESST#30]
Hi,

I'm trying to perform a 2nd round of besst using the scaffolds generated in the first round as the reference, and the MP reads that didn't map to the contigs from the first assembly.

BESST stops in the first library throwing the error described in the error.txt file. Please find also attached the Statistics file.

Any help?
Thanks,
Pedro

[Statistics.txt](https://github.com/ksahlin/BESST/files/232079/Statistics.txt)
[error.txt](https://github.com/ksahlin/BESST/files/232082/error.txt)

**Comment by ksahlin** [comment]
Hi,

I've uploaded a new version of BESST with some recent improvements, could you please try the new version to see if the bug disappears? 

The bug is related to the shape of the insert size distribution. If the bug is still present in the new version, could you run the same commands but adding the parameter -plots? This will plot the insert size distribution of reads (among other things) so that I can get more intuition to what causes the bug.

Thanks for reporting!

**Comment by PedroBarbosa** [comment]
I can't install the new version (2.2). I tried with pip install upgrade, then i completly removed the package and tried again with easy_install

Searching for BESST
Reading http://pypi.python.org/simple/BESST/
Best match: BESST 2.2.0
Downloading https://pypi.python.org/packages/4e/80/af5b5fa53426c1374f8c999f127c178c19160655ee9d61f0304e47a6a88f/BESST-2.2.0.tar.gz#md5=c4f07491ccebe280258d541ceb3a516a
Processing BESST-2.2.0.tar.gz
Running BESST-2.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Y6Og1t/BESST-2.2.0/egg-dist-tmp-g4ZQnG
error: /tmp/easy_install-Y6Og1t/BESST-2.2.0/README.md: No such file or directory

**Comment by ksahlin** [comment]
Oh, yes I get the same error.. I'll look into that..

Meanwhile, since you already have all dependencies installed, it might be easier for you to just pull down the source from github as described here: [installing](https://github.com/ksahlin/BESST/blob/master/docs/INSTALL.md)
If you don't want to run besst from that directory, you could just create a little binary on the format

```
#!/bin/bash
for arg in "$@"; do
    args="$args $arg"
done

/your/path/to/BESST/./runBESST $args
``` 
and place it in your path and name it e.g. "BESST.sh"

**Comment by ksahlin** [comment]
OK, I fixed the broken pip package now! try `pip install BESST` again to see if it works also for you.

**Comment by PedroBarbosa** [comment]
It worked, thanks.

But now, with the '-plots' option, the process stops at pass1 when trying to generate the histogram of the fragment length distribution.

Please find attached the auxiliar files.
[Statistics.txt](https://github.com/ksahlin/BESST/files/238828/Statistics.txt)
[error.txt](https://github.com/ksahlin/BESST/files/238829/error.txt)

**Comment by ksahlin** [comment]
hmm, ok. Can you try without the -plots option to see if the original but still occurs? I'll look into the histogram bug meanwhile.

**Comment by PedroBarbosa** [comment]
Yes, i tried. The error still persists :/

**Comment by ksahlin** [comment]
Regarding the histogram error, I think it has to do with the version of matplotlib you are using, see [stackowerflow answer](http://stackoverflow.com/a/34001464/2060202). Could you check what version of matplotlib you are using and update in that case (if you want to use the -plots option).

I'll get back on the other bug..

**Comment by PedroBarbosa** [comment]
My default python version is 3.5 and all the packages are mantained using anaconda. Despite that, i still have python 2.7 installed. BESST seems to not recognize the last version as default and use the 2.7 instead. Is there a way to tell BESST which python version to use?

I updated the matplotlib version for the python 2.7, but now i get complains about other module:


Traceback (most recent call last):
  File "/usr/local/bin/runBESST", line 415, in <module>
    main(args)
  File "/usr/local/bin/runBESST", line 177, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/usr/local/lib/python2.7/dist-packages/BESST/CreateGraph.py", line 300, in PE
    GiveScoreOnEdges(G, Scaffolds, small_scaffolds, Contigs, param, Information, plot)
  File "/usr/local/lib/python2.7/dist-packages/BESST/CreateGraph.py", line 515, in GiveScoreOnEdges
    gap = lnpe.GapEstimator(param.lognormal_mean, param.lognormal_sigma, param.read_len, samples, len1, c2_len=len2)
  File "/usr/local/lib/python2.7/dist-packages/mathstats/log_normal_param_est.py", line 211, in GapEstimator
    d_ML = get_d_ML_Newton_Raphson(mu, sigma, r, c_min, observations, c_max, d_lower, d_upper, cutoff_approx_level)
  File "/usr/local/lib/python2.7/dist-packages/mathstats/log_normal_param_est.py", line 248, in get_d_ML_Newton_Raphson
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/rcsetup.py", line 34, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: No module named cycler

**Comment by ksahlin** [comment]
There are several ways to do that. I would strongly advise using python version management [pyenv](https://github.com/yyuu/pyenv) and virtual environments [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv). BESST is however not compatible with python3.
 For the matplotlib bug, I think it is some conflicting version problems. I wont look into that further as I think its matplotlib specific and fixing -plots issues is not on the high priority list, sorry. Basically, I think this bug could be solved by creating a fresh python environment for e.g. python2.7.9 using pyenv, then simple issue `pip install BESST` in that environment and that will install all dependencies with correct versions in this particular environment. 

BTW, I'm about to solve the original ZeroDivisionError bug. A commit will hopefully come later in the day.

**Comment by ksahlin** [comment]
I've now uploaded a version of BESST that should fix the original  ZeroDivisionError bug. The bug actually came from mathstats package. So any installation of the most recent BESST should basically make sure to download a newer version of mathstats package. Let me know how it goes.

**Comment by PedroBarbosa** [comment]
I will. But the error with the broken pip is still happening

**Comment by ksahlin** [comment]
Ok, the broken pip was now caused by the dependency package mathstats. I just fixed that so now it should definitely work, as long as you have mathstats v =>0.2.4 I would therefore do:

```
pip install --upgrade mathstats
pip install BESST
```
or similar, to ensure the latest mathstats is there. Let me know if this fixes it, fingers crossed this time....

**Comment by PedroBarbosa** [comment]
Ok, the previous problem is fixed :) Now i got a new error in pass4. Mathstats is updated to the last version. Files attached, if you need the plots i can also send them.

`pip install --upgrade mathstats`

`Requirement already up-to-date: mathstats in /usr/bin/anaconda3/envs/py27/lib/python2.7/site-packages
Requirement already up-to-date: scipy>=0.9 in /usr/bin/anaconda3/envs/py27/lib/python2.7/site-packages (from mathstats)`.


[Statistics.txt](https://github.com/ksahlin/BESST/files/245163/Statistics.txt)
[error.txt](https://github.com/ksahlin/BESST/files/245164/error.txt)

**Comment by ksahlin** [comment]
I've now fixed this bug in latest commit to master + latest version on pip!

However, I must ask you why you have four libraries with almost identical insert size distributions? If you intend to scaffold with them I strongly suggest to merge the reads into one file and map all of them as a single library for best quality, since they are so similar.

**Comment by PedroBarbosa** [comment]
They actually came from different library construction processes, i could expect to observe some variation in the distribution, but yes, they look very similar.. I didn't think that having more passes with the same insert size would affect the quality of the results. I'll merge the bam files then and give BESST a new try.

Thanks for all your help Kristoffer

**Comment by ksahlin** [comment]
It might not affect much, but I still think it's better to merge them. My prediction is that the three following libraries would not do much since they likely contain little additional information, while they could still improve the total information for the first library.

Great! I'll close this issue now. If you have further issues or questions on the scaffolding that are not bugs, shoot me an email.
